### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by chmwzc** [qiboteam/qibochem#53]
@TL231 When I try to install using `pip install .` in a fresh `conda` environment (Python 3.11), I get:
 
```

(qibochem) wongzc@Living-Room:~/repos/qibochem$ (main) pip install .
Processing /home/wongzc/repos/qibochem
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
 
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/home/wongzc/miniforge3/envs/qibochem/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/wongzc/miniforge3/envs/qibochem/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/wongzc/miniforge3/envs/qibochem/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-5s2u83h_/overlay/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 42, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-5s2u83h_/overlay/lib/python3.11/site-packages/poetry/core/factory.py", line 58, in create_poetry
          raise RuntimeError("The Poetry configuration is invalid:\n" + message)
      RuntimeError: The Poetry configuration is invalid:
        - data.documentation must be uri

       [end of output]
 
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
 
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
 
Tried using `poetry install`, I get the same error:
```
(qibochem) wongzc@Living-Room:~/repos/qibochem$ (main) poetry install
 
The Poetry configuration is invalid:
  - data.documentation must be uri
 
```
 
Is it just me, or can anyone else reproduce this? I've tried on a Linux and WSL system, both don't work.

**Comment by TL231** [comment]
I think it might be because in pyproject.toml the `documentation = ""` line is empty, I've just now pushed and update to the dev/docs branch that added the `documentation = "https://qibo.science/qibochem/latest/"` line.
Try that branch and see how it goes.

The main branch still has `documentation = ""` but that should be fixed after merger with dev/docs.

**Comment by chmwzc** [comment]
Yes, it works now, thanks!
